apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-service-with-module
  description: pipeline build and deploy
  annotations:
       harness.io/pipelines: |
         labelA: https://app.harness.io/ng/account/VRuJ8-dqQH6QZgAtoBr66g/cd/orgs/default/projects/TESTINTELLIGENCEMASTER/pipelines/test/pipeline-studio/?storeType=INLINE |
         labelB: https://app.harness.io/ng/account/VRuJ8-dqQH6QZgAtoBr66g/cd/orgs/default/projects/TESTINTELLIGENCEMASTER/pipelines/test/pipeline-studio/?storeType=INLINE
       harness.io/project-url: |
          labelA: https://qa.harness.io/ng/account/25NKDX79QPC-YTyninmxRQ/module/iacm/orgs/default/projects/william/dashboard |
          labelB: https://qa.harness.io/ng/account/25NKDX79QPC-YTyninmxRQ/module/iacm/orgs/default/projects/william/dashboard
  tags:
    - java
  
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
spec:
  type: service
  lifecycle: experimental
  owner: idpplayacc
